"""Update schema with new fields

Revision ID: 5989ad64fa6b
Revises: 
Create Date: 2025-12-13 11:29:38.471780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5989ad64fa6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tongtien', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.alter_column('trangthai',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('cho_xac_nhan', 'dang_giao', 'hoan_thanh', 'huy', name='order_status_enum'),
               existing_nullable=True)
        batch_op.alter_column('diachi_giaohang',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=225),
               nullable=False)
        batch_op.alter_column('hoten',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('sdt',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('payment_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.drop_column('tongdon')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loai', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gioi_tinh', sa.Enum('Nam', 'Nữ', 'Unisex', name='gioi_tinh_enum'), nullable=True))
        batch_op.alter_column('trang_thai',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Con_hang', 'Het_hang', 'Ngung_ban', name='trang_thai_enum'),
               existing_nullable=True)
        batch_op.drop_column('gia_tien')
        batch_op.drop_column('bai')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('matkhau',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.alter_column('hoten',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('diachi',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'customer', name='role_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'customer', name='role_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('diachi',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('hoten',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('matkhau',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bai', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gia_tien', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.alter_column('trang_thai',
               existing_type=sa.Enum('Con_hang', 'Het_hang', 'Ngung_ban', name='trang_thai_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('gioi_tinh')
        batch_op.drop_column('loai')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tongdon', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.alter_column('payment_token',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('sdt',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('hoten',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('diachi_giaohang',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('trangthai',
               existing_type=sa.Enum('cho_xac_nhan', 'dang_giao', 'hoan_thanh', 'huy', name='order_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('tongtien')

    # ### end Alembic commands ###
